### ISSUE TITLE
Not playing

### ISSUE THREAD

**Issue by fardeen619** [naseif/Eyesense-Music-Bot#10]
When i play song it gives error in console FFmpeg/avconv not found

**Comment by naseif** [comment]
Hey @fardeen619, this issue has nothing to do with bot itself, please make sure to install **ffmpeg** on your system and add it to the path if you are using windows. Technically you do not have to do this on your own since ffmpeg-static is already included in package.json. Please make sure to install the required packages again with `npm i `
